
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.form.field.Number": "../../../../ext/src/form/field/Number.js",
  "Ext.form.RadioGroup": "../../../../ext/src/form/RadioGroup.js",
  "Ext.rtl.EventObjectImpl": "../../../../ext/src/rtl/EventObject.js",
  "Calculator.Application": "app/application.js",
  "Ext.form.CheckboxManager": "../../../../ext/src/form/CheckboxManager.js",
  "Ext.form.Label": "../../../../ext/src/form/Label.js",
  "Ext.form.field.Field": "../../../../ext/src/form/field/Field.js",
  "Ext.form.field.TextArea": "../../../../ext/src/form/field/TextArea.js",
  "Ext.form.FieldSet": "../../../../ext/src/form/FieldSet.js",
  "Ext.form.field.Text": "../../../../ext/src/form/field/Text.js",
  "Ext.form.field.Display": "../../../../ext/src/form/field/Display.js",
  "Ext.form.FieldAncestor": "../../../../ext/src/form/FieldAncestor.js",
  "Ext.form.field.VTypes": "../../../../ext/src/form/field/VTypes.js",
  "Ext": "../../../../ext/src",
  "Ext.form.CheckboxGroup": "../../../../ext/src/form/CheckboxGroup.js",
  "Ext.form.field.Date": "../../../../ext/src/form/field/Date.js",
  "Ext.form.field.Checkbox": "../../../../ext/src/form/field/Checkbox.js",
  "Ext.form.field.Radio": "../../../../ext/src/form/field/Radio.js",
  "Ext.form.field.HtmlEditor": "../../../../ext/src/form/field/HtmlEditor.js",
  "Ext.form.RadioManager": "../../../../ext/src/form/RadioManager.js",
  "Ext.form.field.File": "../../../../ext/src/form/field/File.js",
  "Ext.form.field.Time": "../../../../ext/src/form/field/Time.js",
  "Ext.form.field.Picker": "../../../../ext/src/form/field/Picker.js",
  "Ext.form.Panel": "../../../../ext/src/form/Panel.js",
  "Ext.form.field.Spinner": "../../../../ext/src/form/field/Spinner.js",
  "Ext.form.field.Base": "../../../../ext/src/form/field/Base.js",
  " Ext.Msg": "../../../../ext/src/window/MessageBox.js",
  "Ext.form.Labelable": "../../../../ext/src/form/Labelable.js",
  "Ext.form.field.Hidden": "../../../../ext/src/form/field/Hidden.js",
  "Ext.form": "../../src/form",
  "Ext.form.FieldContainer": "../../../../ext/src/form/FieldContainer.js",
  "Ext.form.field.Trigger": "../../../../ext/src/form/field/Trigger.js",
  "Calculator": "app",
  "Ext.form.action": "../../../../ext/src/form/action",
  "Ext.form.field.FileButton": "../../../../ext/src/form/field/FileButton.js",
  "Ext.form.Basic": "../../../../ext/src/form/Basic.js",
  "Ext.form.field.ComboBox": "../../../../ext/src/form/field/ComboBox.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.form.field.calculator.Picker": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Calculator.view.Viewport": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.form.field.calculator.Calculator": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Calculator.Application": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ]
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.form.field.calculator.Picker": [
    "widget.calculatorpicker"
  ],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Calculator.view.Viewport": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.form.field.calculator.Calculator": [
    "widget.calculatorfield"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Calculator.Application": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ]
});
